In [1]:
# Imports, paths and load staging data

from pathlib import Path
import re
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd().parent

RAW_FILE = (
    PROJECT_ROOT
    / "Raw_Data"
    / "NFHS_5_India_Districts_Factsheet_Data.xls"
)
STAGING_FILE = PROJECT_ROOT / "Staging" / "nfhs_staging.csv"

CLEAN_DIR = PROJECT_ROOT / "Cleaned_Data"
REPORT_DIR = (
    PROJECT_ROOT
    / "Reports"
    / "03_data_cleaning_and_validation"
)

CLEAN_DIR.mkdir(parents=True, exist_ok=True)
REPORT_DIR.mkdir(parents=True, exist_ok=True)

CLEAN_FILE = CLEAN_DIR / "nfhs_cleaned.csv"
CLEANING_LOG_FILE = CLEAN_DIR / "cleaning_log.csv"
QUALITY_REPORT_FILE = REPORT_DIR / "data_quality_issues.csv"

if not STAGING_FILE.exists():
    raise FileNotFoundError(
        f"Staging file not found: {STAGING_FILE}. Run Notebook 2 first."
    )

if not RAW_FILE.exists():
    raise FileNotFoundError(f"Raw source file not found: {RAW_FILE}")

print("Notebook 3 paths configured.")
print(f"Input: {STAGING_FILE}")
print(f"Cleaned output: {CLEAN_FILE}")
print(f"Reports: {REPORT_DIR}")

Notebook 3 paths configured.
Input: C:\PORTFOLIO\NFHS-5-Healthcare-Analytics-District-Intelligence\Staging\nfhs_staging.csv
Cleaned output: C:\PORTFOLIO\NFHS-5-Healthcare-Analytics-District-Intelligence\Cleaned_Data\nfhs_cleaned.csv
Reports: C:\PORTFOLIO\NFHS-5-Healthcare-Analytics-District-Intelligence\Reports\03_data_cleaning_and_validation

In [2]:
# Load data and identify percentage indicators

df_staging = pd.read_csv(
    STAGING_FILE,
    low_memory=False
)

df_clean = df_staging.copy()

df_raw_headers = pd.read_excel(
    RAW_FILE,
    sheet_name="Sheet1",
    engine="xlrd",
    nrows=0
)

def standardize_column_name(column):
    """Standardise column names to lowercase snake_case."""
    column = re.sub(
        r"[^a-zA-Z0-9]+",
        "_",
        str(column).strip().lower()
    )
    return column.strip("_")


# Reproduce Notebook 2's column naming so source headers
# can be matched to their staged column names.
source_column_names = []
seen = {}

for original_column in df_raw_headers.columns:
    name = standardize_column_name(original_column)
    count = seen.get(name, 0)

    source_column_names.append(
        name if count == 0 else f"{name}_{count}"
    )
    seen[name] = count + 1

percentage_columns = []

for original_column, staged_column in zip(
    df_raw_headers.columns,
    source_column_names
):
    original_text = str(original_column).lower()

    if (
        "%" in original_text
        or "percent" in original_text
        or "percentage" in original_text
    ):
        if staged_column in df_clean.columns:
            percentage_columns.append(staged_column)

required_columns = {"district_names", "state_ut"}

if not required_columns.issubset(df_clean.columns):
    raise ValueError("Required district/state columns are missing.")

if df_clean.shape != df_staging.shape:
    raise ValueError("Staging structure changed unexpectedly.")

print(f"Rows loaded: {len(df_clean):,}")
print(f"Columns loaded: {len(df_clean.columns):,}")
print(f"Percentage indicators identified: {len(percentage_columns):,}")
print(percentage_columns)

Rows loaded: 707
Columns loaded: 109
Percentage indicators identified: 101
['female_population_age_6_years_and_above_who_ever_attended_school', 'population_below_age_15_years', 'children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority', 'deaths_in_the_last_3_years_registered_with_the_civil_authority', 'population_living_in_households_with_electricity', 'population_living_in_households_with_an_improved_drinking_water_source1', 'population_living_in_households_that_use_an_improved_sanitation_facility2', 'households_using_clean_fuel_for_cooking3', 'households_using_iodized_salt', 'households_with_any_usual_member_covered_under_a_health_insurance_financing_scheme', 'children_age_5_years_who_attended_pre_primary_school_during_the_school_year_2019_20', 'women_age_15_49_who_are_literate4', 'women_age_15_49_with_10_or_more_years_of_schooling', 'women_age_20_24_years_married_before_age_18_years', 'births_in_the_5_years_preceding_the_survey_that_are_third_or_higher_order', 'women_age_15_19_years_who_were_already_mothers_or_pregnant_at_the_time_of_the_survey', 'women_age_15_24_years_who_use_hygienic_methods_of_protection_during_their_menstrual_period5', 'current_use_of_family_planning_methods_currently_married_women_age_15_49_years_any_method6', 'current_use_of_family_planning_methods_currently_married_women_age_15_49_years_any_modern_method6', 'current_use_of_family_planning_methods_currently_married_women_age_15_49_years_female_sterilization', 'current_use_of_family_planning_methods_currently_married_women_age_15_49_years_male_sterilization', 'current_use_of_family_planning_methods_currently_married_women_age_15_49_years_iud_ppiud', 'current_use_of_family_planning_methods_currently_married_women_age_15_49_years_pill', 'current_use_of_family_planning_methods_currently_married_women_age_15_49_years_condom', 'current_use_of_family_planning_methods_currently_married_women_age_15_49_years_injectables', 'total_unmet_need_for_family_planning_currently_married_women_age_15_49_years_7', 'unmet_need_for_spacing_currently_married_women_age_15_49_years_7', 'health_worker_ever_talked_to_female_non_users_about_family_planning', 'current_users_ever_told_about_side_effects_of_current_method_of_family_planning8', 'mothers_who_had_an_antenatal_check_up_in_the_first_trimester_for_last_birth_in_the_5_years_before_the_survey', 'mothers_who_had_at_least_4_antenatal_care_visits_for_last_birth_in_the_5_years_before_the_survey', 'mothers_whose_last_birth_was_protected_against_neonatal_tetanus_for_last_birth_in_the_5_years_before_the_survey_9', 'mothers_who_consumed_iron_folic_acid_for_100_days_or_more_when_they_were_pregnant_for_last_birth_in_the_5_years_before_the_survey', 'mothers_who_consumed_iron_folic_acid_for_180_days_or_more_when_they_were_pregnant_for_last_birth_in_the_5_years_before_the_survey', 'registered_pregnancies_for_which_the_mother_received_a_mother_and_child_protection_mcp_card_for_last_birth_in_the_5_years_before_the_survey', 'mothers_who_received_postnatal_care_from_a_doctor_nurse_lhv_anm_midwife_other_health_personnel_within_2_days_of_delivery_for_last_birth_in_the_5_years_before_the_survey', 'children_born_at_home_who_were_taken_to_a_health_facility_for_a_check_up_within_24_hours_of_birth_for_last_birth_in_the_5_years_before_the_survey', 'children_who_received_postnatal_care_from_a_doctor_nurse_lhv_anm_midwife_other_health_personnel_within_2_days_of_delivery_for_last_birth_in_the_5_years_before_the_survey', 'institutional_births_in_the_5_years_before_the_survey', 'institutional_births_in_public_facility_in_the_5_years_before_the_survey', 'home_births_that_were_conducted_by_skilled_health_personnel_in_the_5_years_before_the_survey_10', 'births_attended_by_skilled_health_personnel_in_the_5_years_before_the_survey_10', 'births_delivered_by_caesarean_section_in_the_5_years_before_the_survey', 'births_in_a_private_health_facility_that_were_delivered_by_caesarean_section_in_the_5_years_before_the_survey', 'births_in_a_public_health_facility_that_were_delivered_by_caesarean_section_in_the_5_years_before_the_survey', 'children_age_12_23_months_fully_vaccinated_based_on_information_from_either_vaccination_card_or_mother_s_recall11', 'children_age_12_23_months_fully_vaccinated_based_on_information_from_vaccination_card_only12', 'children_age_12_23_months_who_have_received_bcg', 'children_age_12_23_months_who_have_received_3_doses_of_polio_vaccine13', 'children_age_12_23_months_who_have_received_3_doses_of_penta_or_dpt_vaccine', 'children_age_12_23_months_who_have_received_the_first_dose_of_measles_containing_vaccine_mcv', 'children_age_24_35_months_who_have_received_a_second_dose_of_measles_containing_vaccine_mcv', 'children_age_12_23_months_who_have_received_3_doses_of_rotavirus_vaccine14', 'children_age_12_23_months_who_have_received_3_doses_of_penta_or_hepatitis_b_vaccine', 'children_age_9_35_months_who_received_a_vitamin_a_dose_in_the_last_6_months', 'children_age_12_23_months_who_received_most_of_their_vaccinations_in_a_public_health_facility', 'children_age_12_23_months_who_received_most_of_their_vaccinations_in_a_private_health_facility', 'prevalence_of_diarrhoea_in_the_2_weeks_preceding_the_survey_children_under_age_5_years', 'children_with_diarrhoea_in_the_2_weeks_preceding_the_survey_who_received_oral_rehydration_salts_ors_children_under_age_5_years', 'children_with_diarrhoea_in_the_2_weeks_preceding_the_survey_who_received_zinc_children_under_age_5_years', 'children_swith_diarrhoea_in_the_2_weeks_preceding_the_survey_taken_to_a_health_facility_or_health_provider_children_under_age_5_years', 'children_prevalence_of_symptoms_of_acute_respiratory_infection_ari_in_the_2_weeks_preceding_the_survey_children_under_age_5_years', 'children_with_fever_or_symptoms_of_ari_in_the_2_weeks_preceding_the_survey_taken_to_a_health_facility_or_health_provider_children_under_age_5_years', 'children_under_age_3_years_breastfed_within_one_hour_of_birth15', 'children_under_age_6_months_exclusively_breastfed16', 'children_age_6_8_months_receiving_solid_or_semi_solid_food_and_breastmilk16', 'breastfeeding_children_age_6_23_months_receiving_an_adequate_diet16_17', 'non_breastfeeding_children_age_6_23_months_receiving_an_adequate_diet16_17', 'total_children_age_6_23_months_receiving_an_adequate_diet16_17', 'children_under_5_years_who_are_stunted_height_for_age_18', 'children_under_5_years_who_are_wasted_weight_for_height_18', 'children_under_5_years_who_are_severely_wasted_weight_for_height_19', 'children_under_5_years_who_are_underweight_weight_for_age_18', 'children_under_5_years_who_are_overweight_weight_for_height_20', 'women_age_15_49_years_whose_body_mass_index_bmi_is_below_normal_bmi_18_5_kg_m2_21', 'women_age_15_49_years_who_are_overweight_or_obese_bmi_25_0_kg_m2_21', 'women_age_15_49_years_who_have_high_risk_waist_to_hip_ratio_0_85', 'children_age_6_59_months_who_are_anaemic_11_0_g_dl_22', 'non_pregnant_women_age_15_49_years_who_are_anaemic_12_0_g_dl_22', 'pregnant_women_age_15_49_years_who_are_anaemic_11_0_g_dl_22', 'all_women_age_15_49_years_who_are_anaemic22', 'all_women_age_15_19_years_who_are_anaemic22', 'women_age_15_years_and_above_with_high_141_160_mg_dl_blood_sugar_level23', 'women_age_15_years_and_above_wih_very_high_160_mg_dl_blood_sugar_level23', 'women_age_15_years_and_above_wih_high_or_very_high_140_mg_dl_blood_sugar_level_or_taking_medicine_to_control_blood_sugar_level23', 'men_age_15_years_and_above_wih_high_141_160_mg_dl_blood_sugar_level23', 'men_age_15_years_and_above_wih_very_high_160_mg_dl_blood_sugar_level23', 'men_age_15_years_and_above_wih_high_or_very_high_140_mg_dl_blood_sugar_level_or_taking_medicine_to_control_blood_sugar_level23', 'women_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140_159_mm_of_hg_and_or_diastolic_90_99_mm_of_hg', 'women_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_160_mm_of_hg_and_or_diastolic_100_mm_of_hg', 'women_age_15_years_and_above_wih_elevated_blood_pressure_systolic_140_mm_of_hg_and_or_diastolic_90_mm_of_hg_or_taking_medicine_to_control_blood_pressure', 'men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140_159_mm_of_hg_and_or_diastolic_90_99_mm_of_hg', 'men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_160_mm_of_hg_and_or_diastolic_100_mm_of_hg', 'men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_140_mm_of_hg_and_or_diastolic_90_mm_of_hg_or_taking_medicine_to_control_blood_pressure', 'women_age_30_49_years_ever_undergone_a_screening_test_for_cervical_cancer', 'women_age_30_49_years_ever_undergone_a_breast_examination_for_breast_cancer', 'women_age_30_49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer', 'women_age_15_years_and_above_who_use_any_kind_of_tobacco', 'men_age_15_years_and_above_who_use_any_kind_of_tobacco', 'women_age_15_years_and_above_who_consume_alcohol', 'men_age_15_years_and_above_who_consume_alcohol']

In [3]:
# Standardise missing markers and data types

cleaning_log = []

unavailable_markers = [
    "*", "-", "NA", "N/A", "NULL", "NONE"
]

identifier_columns = ["district_names", "state_ut"]

for column in identifier_columns:
    df_clean[column] = (
        df_clean[column]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

# Convert known unavailable markers to missing values.
for column in df_clean.columns:
    if column in identifier_columns:
        continue

    text_values = df_clean[column].astype("string").str.strip()
    normalized_values = text_values.str.upper()

    unavailable_mask = (
        normalized_values.isin(unavailable_markers)
        | text_values.eq("")
    ).fillna(False)

    unavailable_count = int(unavailable_mask.sum())

    if unavailable_count:
        df_clean.loc[unavailable_mask, column] = np.nan

        cleaning_log.append({
            "column": column,
            "action": "Replace unavailable markers with missing",
            "affected_rows": unavailable_count,
            "reason": "Recognised unavailable-value marker"
        })

    # Convert indicator values to numeric where possible.
    df_clean[column] = pd.to_numeric(
        df_clean[column],
        errors="coerce"
    )

print("Unavailable markers standardised.")
print(f"Numeric indicator columns processed: {len(df_clean.columns) - 2:,}")
print(f"Missing values after conversion: {df_clean.isna().sum().sum():,}")

Unavailable markers standardised.
Numeric indicator columns processed: 107
Missing values after conversion: 4,132

In [4]:
# Identify and handle invalid indicator values

quality_issues = []

# Validate percentage indicators.
for column in percentage_columns:
    numeric_values = pd.to_numeric(
        df_clean[column],
        errors="coerce"
    )

    invalid_mask = (
        numeric_values.notna()
        & ~numeric_values.between(0, 100)
    )

    for row_index in df_clean.index[invalid_mask]:
        quality_issues.append({
            "row_index": int(row_index),
            "district_names": df_clean.at[row_index, "district_names"],
            "state_ut": df_clean.at[row_index, "state_ut"],
            "column": column,
            "observed_value": numeric_values.at[row_index],
            "issue_type": "Percentage outside 0-100",
            "action": "Replaced with missing; verify source"
        })

    affected_count = int(invalid_mask.sum())

    if affected_count:
        df_clean.loc[invalid_mask, column] = np.nan

        cleaning_log.append({
            "column": column,
            "action": "Set out-of-range percentage values to missing",
            "affected_rows": affected_count,
            "reason": "Percentage indicators must be within 0-100"
        })

# Flag negative values only in indicators whose names indicate
# non-negative expenditure or sex-ratio measures.
non_negative_keywords = [
    "expenditure",
    "sex_ratio"
]

for column in df_clean.columns:
    if column in identifier_columns:
        continue

    if not any(
        keyword in column.lower()
        for keyword in non_negative_keywords
    ):
        continue

    numeric_values = pd.to_numeric(
        df_clean[column],
        errors="coerce"
    )

    invalid_mask = (
        numeric_values.notna()
        & numeric_values.lt(0)
    )

    for row_index in df_clean.index[invalid_mask]:
        quality_issues.append({
            "row_index": int(row_index),
            "district_names": df_clean.at[row_index, "district_names"],
            "state_ut": df_clean.at[row_index, "state_ut"],
            "column": column,
            "observed_value": numeric_values.at[row_index],
            "issue_type": "Negative value in non-negative indicator",
            "action": "Replaced with missing; verify source"
        })

    affected_count = int(invalid_mask.sum())

    if affected_count:
        df_clean.loc[invalid_mask, column] = np.nan

        cleaning_log.append({
            "column": column,
            "action": "Set negative indicator values to missing",
            "affected_rows": affected_count,
            "reason": "Indicator is expected to be non-negative"
        })

quality_report = pd.DataFrame(
    quality_issues,
    columns=[
        "row_index",
        "district_names",
        "state_ut",
        "column",
        "observed_value",
        "issue_type",
        "action"
    ]
)

quality_report.to_csv(
    QUALITY_REPORT_FILE,
    index=False
)

print(f"Quality issues identified: {len(quality_report):,}")
print(f"Quality report: {QUALITY_REPORT_FILE}")

if not quality_report.empty:
    display(
        quality_report.groupby("issue_type")
        .size()
        .reset_index(name="issue_count")
    )
else:
    print("No values violated the configured indicator rules.")

Quality issues identified: 5,069
Quality report: C:\PORTFOLIO\NFHS-5-Healthcare-Analytics-District-Intelligence\Reports\03_data_cleaning_and_validation\data_quality_issues.csv

                                 issue_type  issue_count
0  Negative value in non-negative indicator           16
1                  Percentage outside 0-100         5053

In [5]:
# Correct the state spelling and record the action

source_state = "Maharastra"
corrected_state = "Maharashtra"

correction_mask = df_clean["state_ut"].eq(source_state).fillna(False)
correction_count = int(correction_mask.sum())

if correction_count:
    df_clean.loc[correction_mask, "state_ut"] = corrected_state

    cleaning_log.append({
        "column": "state_ut",
        "action": "Standardise state spelling",
        "affected_rows": correction_count,
        "reason": f"{source_state} changed to {corrected_state}"
    })

print(f"State spelling corrections: {correction_count}")
print(
    "Remaining Maharastra rows:",
    int(df_clean["state_ut"].eq(source_state).sum())
)

State spelling corrections: 36
Remaining Maharastra rows: 0

In [6]:
# Validate identifiers and district/state combinations

# Identify missing or blank identifiers.
missing_identifier_mask = (
    df_clean["district_names"].isna()
    | df_clean["district_names"].eq("")
    | df_clean["state_ut"].isna()
    | df_clean["state_ut"].eq("")
)

missing_identifiers = df_clean.loc[
    missing_identifier_mask,
    ["district_names", "state_ut"]
].copy()

# Identify duplicate district/state combinations.
duplicate_pairs = df_clean.loc[
    df_clean.duplicated(
        subset=["district_names", "state_ut"],
        keep=False
    ),
    ["district_names", "state_ut"]
].sort_values(["state_ut", "district_names"])

# Identify district names associated with multiple states.
district_state_conflicts = (
    df_clean.dropna(subset=["district_names", "state_ut"])
    .groupby("district_names")["state_ut"]
    .nunique()
    .loc[lambda counts: counts > 1]
    .rename("state_count")
    .reset_index()
)

missing_identifiers.to_csv(
    REPORT_DIR / "missing_identifiers.csv",
    index=False
)

duplicate_pairs.to_csv(
    REPORT_DIR / "duplicate_district_state_pairs.csv",
    index=False
)

district_state_conflicts.to_csv(
    REPORT_DIR / "district_names_multiple_states.csv",
    index=False
)

print(f"Rows with missing identifiers: {len(missing_identifiers):,}")
print(f"Rows in duplicate pairs: {len(duplicate_pairs):,}")
print(
    "District names occurring in multiple states:",
    len(district_state_conflicts)
)

display(district_state_conflicts)

Rows with missing identifiers: 0
Rows in duplicate pairs: 0
District names occurring in multiple states: 8

  district_names  state_count
0     Aurangabad            2
1      Balrampur            2
2        Bijapur            2
3       Bilaspur            2
4        Chandel            2
5       Hamirpur            2
6     Pratapgarh            2
7        Raigarh            2

In [7]:
# Save the cleaned data and cleaning log

# Confirm that cleaning has not changed the dataset structure.
assert df_clean.shape == df_staging.shape, (
    "Cleaning changed the row or column count."
)

if not missing_identifiers.empty:
    raise ValueError(
        "Missing district/state identifiers remain. "
        "Review the missing_identifiers report."
    )

if not duplicate_pairs.empty:
    raise ValueError(
        "Duplicate district-state pairs remain. "
        "Review the duplicate_district_state_pairs report."
    )

if df_clean["state_ut"].eq("Maharastra").any():
    raise ValueError("Uncorrected Maharastra values remain.")

df_clean.to_csv(
    CLEAN_FILE,
    index=False
)

pd.DataFrame(
    cleaning_log,
    columns=["column", "action", "affected_rows", "reason"]
).to_csv(
    CLEANING_LOG_FILE,
    index=False
)

print(f"Cleaned dataset saved: {CLEAN_FILE}")
print(f"Cleaning log saved: {CLEANING_LOG_FILE}")
print(f"Quality report saved: {QUALITY_REPORT_FILE}")
print(f"Cleaned shape: {df_clean.shape}")

Cleaned dataset saved: C:\PORTFOLIO\NFHS-5-Healthcare-Analytics-District-Intelligence\Cleaned_Data\nfhs_cleaned.csv
Cleaning log saved: C:\PORTFOLIO\NFHS-5-Healthcare-Analytics-District-Intelligence\Cleaned_Data\cleaning_log.csv
Quality report saved: C:\PORTFOLIO\NFHS-5-Healthcare-Analytics-District-Intelligence\Reports\03_data_cleaning_and_validation\data_quality_issues.csv
Cleaned shape: (707, 109)

In [8]:
# Reload and verify saved outputs

df_verified = pd.read_csv(
    CLEAN_FILE,
    low_memory=False
)

assert df_verified.shape == df_staging.shape
assert df_verified["district_names"].notna().all()
assert df_verified["state_ut"].notna().all()

assert not df_verified.duplicated(
    ["district_names", "state_ut"]
).any()

assert not df_verified["state_ut"].eq("Maharastra").any()

print("Final saved-file validation passed.")
print(f"Rows: {len(df_verified):,}")
print(f"Columns: {len(df_verified.columns):,}")
print(
    "Maharashtra rows:",
    int(df_verified["state_ut"].eq("Maharashtra").sum())
)
print(f"Reports folder: {REPORT_DIR}")

Final saved-file validation passed.
Rows: 707
Columns: 109
Maharashtra rows: 36
Reports folder: C:\PORTFOLIO\NFHS-5-Healthcare-Analytics-District-Intelligence\Reports\03_data_cleaning_and_validation